// tslint:disable max-line-length

export const quotes = [
  `A large proportion of Britain's Asian population fail to pass the cricket test. Which side do they cheer for?`,
  `As I look ahead, I am filled with foreboding. Like the Roman, I seem to see the River Tiber foaming with much blood`,
  `Ban this sick filth`,
  `But many of the unemployed had become static and didn't know that if they got on a bus for an hour's journey, they'd be in Cardiff and could look for the jobs there`,
  `Hoorah for the blackshirts!`,
  `I blame all of this on stealth taxes and permissive education in the 1960s`,
  `I can no longer sit back and allow Communist infiltration, Communist indoctrination, Communist subversion and the international Communist conspiracy to sap and impurify all of our precious bodily fluids`,
  `I grew up in the 1930s with an unemployed father. He did not riot. He got on his bike and looked for work, and he went on looking until he found it`,
  `I have always said if you want a speech, ask a man. If you want something done, ask a woman`,
  `I like sponge`,
  `I think hanging is too good for them; Its time to consider the reintroduction of crucifixion, especially for criminals`,
  `If only we had a privatised National Identity scheme this would never have happened`,
  `Its the terrorists fault. Watch my eyes. Te-rror-ists. Now I can say anything I like and you'll think it makes sense somehow. Brilliant. Te-rror-is-ts`,
  `Multiculturalism has failed utterly`,
  `Things got out of hand and we'd had a few drinks. We smashed the place up and Boris set fire to the toilets`,
  `Waterboarding is not torture`,
  `We need a lot less of the passive tolerance of recent years and much more active, muscular liberalism. Especially for the blacks`,
  `a glorious thousand-year reich seems like the only practical choice to stem the tide of economic migrants`,
  `arbeit macht frei`,
  `kill the commie swine`,
  `make no mistake if this is allowed to continue Armageddon shall surely be upon us and woe betide all who would seek to impose upon us a surveillance society. For on that day the right shall inherit the Earth!`,
  `new Age travellers? Not in this age. Not in any age. Let others speak for these New Age travellers. We will speak for their victims`,
  `our prisons are like holiday camps`,
  `read my lips; no new taxes`,
  `society needs to condemn a little more and understand a little less`,
  `surely something can be done?`,
  `the day of the yob is upon us`,
  `the lady's not for turning`,
  `these dole-scrounging n'er-do-wells must be eliminated at all costs`,
  `was it for this politically correct insanity that I fought and died in eight world wars? I think not!`,
  `we are a grandmother`,
  `we are coming slowly, painfully to an autumn of understanding, I hope it will be followed by a winter of common sense`,
  `yet again these oafs have destroyed my evening`,
  `kill the poor`,
  `I've probably had hundreds of spermatophores ejaculate on my fingers and never felt a sting.`,
  `What's the big deal? It's just pictures or footage of people having sex together, after all.`,
];
