export const rightWingers = [
  `Margaret Thatcher`,
  `Enoch Powell`,
  `Boris Johnson`,
  `The deputy commissioner of the Metropolitan Police`,
  `an unnamed source`,
  `Mr I.P.Freely of Tunbridge Wells`,
  `a hardworking family`,
  `Beyonce`,
  `Norris McWhirter, speaking posthumously`,
  `Paul Dacre`,
  `David Cameron`,
  `Michael Howerd`,
  `John Major`,
  `Vince Cable`,
  `Theresa May`,
  `Amanda Platell`,
  `Ian Dunkin-Donuts`,
  `Jeremy Clarkson`,
  `Richard Littlejohn`,
  `Lala from the teletubbies`,
  `The Queen`,
  `Jim Davidson`,
  `Bernard Manning`,
  `Anne Widdecombe`,
  `Jonathan Aitkin`,
  `Bernard Jenkin`,
  `Theresa May`,
  `Norman Tebbit`,
  `Jacob Rees-Mogg`,
  `David Cameron`,
  `Nick Clegg`,
  `George Osborne`,
  `The Pope`,
  `The English People`,
  `James May`,
  `Angela Merkel`,
  `Winston Churchill, speaking through a medium`,
  `Nicolas Sarkozy`,
  `a homeowner`,
  `some bloke in the pub`,
  `Conservative head office`,
  `Piers Morgan`,
  `Penis Morgan`,
  `Tommy Robinsons fruit drink`,
  `Jeremy Hunt`,
  `Katie Hopkins`,
  `a middle class child`,
  `Donald Trump`,
  `P.I. Staker`,
];
