export const scapegoats = [
  `Al Quaeda bosses`,
  `Cherie Blair's friends`,
  `Eastern European terror gangs`,
  `French unions`,
  `Guardian-reading do-gooders`,
  `Islamist youths`,
  `Jeremy Corbyn-admiring lefty scum`,
  `Jeremy Corbyn admirers`,
  `Jeremy Corbyn fans`,
  `Noam Chomsky devotees`,
  `Twitter users`,
  `anarchists calling themselves the Wombles`,
  `anarchists`,
  `asylum seekers`,
  `bleeding heart liberals`,
  `benefit scrounges`,
  `chavs`,
  `coloureds`,
  `communist-sympathisers`,
  `Corbynites`,
  `criminal gangs from Eastern Europe`,
  `cyber criminals`,
  `cyberterrorists`,
  `enviro-Mental-ists`,
  `extremists`,
  `feminazis`,
  `followers of Hugo Chavez`,
  `gangs of black youths`,
  `gangs of children, some still in their prams`,
  `glue-sniffing teenagers`,
  `gay Liberal Democrats`,
  `council house dwellers`,
  `minimum wage workers`,
  `gypsies`,
  `homosexuals`,
  `transgenders`,
  `hoodies`,
  `hoody-wearing layabouts`,
  `hooligans`,
  `hunt sabateours`,
  `insane Brussels bureaucrats`,
  `lesbians`,
  `butch lesbians`,
  `louts`,
  `miners, bent on revenge`,
  `migrants`,
  `paedophiles`,
  `ravers smashed out of their tiny minds on ecstasy`,
  `remoaners`,
  `smelly vegans`,
  `so-called new age travellers`,
  `so-called refugees`,
  `teachers indoctrinated with sixties liberal values`,
  `the French`,
  `the politically correct Islington lefties`,
  `the poor`,
  `the unions`,
  `thugs`,
  `unemployed layabouts demanding benefits with menace`,
  `women`,
  `yobs wearing hoodies and baseball caps`,
  `young muslim men`,
  `young single mothers`,
  `young doctors`,
  `junior doctors`,
  `youths`,
  `opinionated university students`,
  `genderqueer teenagers`,
  `Welsh speakers`,
  `the Welsh`,
  `drunken Scots `,
  `northerners`,
  `gingers`,
  `entitled millenials`,
  `Calais stowaways`,
  `murderers and rapists`,
  `Somali pirates`,
  `animal rights activists`,
  `angry cyclists in lycra`,
  `muslim women wearing burkas`,
];
